### ISSUE TITLE
test data and instructions

### ISSUE THREAD

**Issue by epoc88** [stereolabs/zed-yolo#6]
Could you provide test images and a brief about the test data structure. 
i.e. left image, and depth image.  are they in same folder or different folder?
would be kind if you provide svo files as well.

**Comment by adujardin** [comment]
Hi,
In the current state, the only accepted input is through the ZED SDK, which means it must either be: a ZED camera plugged in, or an SVO file which is a recording of ZED sequence.

However, since it's open source you could modify the samples to bypass the ZED SDK to directly load the left RGB image and the depth (such data must have been exported before).

We currently don't provide SVO files suitable for object detection, unfortunately.
